### ISSUE TITLE
Shadow possible? 

### ISSUE THREAD

**Issue by Rainer-Lang** [TangoAgency/avatar-view#12]

**Comment by radzio** [comment]
Shadow what?

**Comment by Rainer-Lang** [comment]
Like here: https://github.com/lopspower/CircularImageView

**Comment by radzio** [comment]
@Rainer-Lang we are not planning to implement this in near future. But PRs are welcome so fell free to add this functionality.

**Comment by Rainer-Lang** [comment]
@radzio It would be a 2nice-to-have", but it's not necessary. The Glide-support is essential for me - for example.
I'm closing this issue for now.
