### ISSUE TITLE
gradle dependency not added in project 

### ISSUE THREAD

**Issue by sushilbishnoi** [TangoAgency/avatar-view#30]
![screen shot 2018-03-13 at 10 52 36 am](https://user-images.githubusercontent.com/31500650/37323954-c2c87eac-26ac-11e8-833f-7798cbf965e4.png)
![screen shot 2018-03-13 at 10 52 52 am](https://user-images.githubusercontent.com/31500650/37323955-c2fbba1a-26ac-11e8-9a92-c5e030926371.png)

**Comment by radzio** [comment]
You have to replace `{latest_release}` literally with the latest version. 

https://bintray.com/tangoagency/maven/avatar-view/0.0.2

**Comment by sushilbishnoi** [comment]
thanks @radzio

**Comment by sushilbishnoi** [comment]
@radzio can we add name with initial letter in circle like eg:- sushil bishnoi show in circle SB
